### ISSUE TITLE
Salt Cell Setpoint No Longer Provided by Integration

### ISSUE THREAD

**Issue by FlaMike** [Crewski/njsPC-HA#12]
I upgraded to your latest release version after the heater on/off issue was resolved.

After installing the latest version, the entity "number.intellichlor_20_pool_setpoint" is no longer available through the integration.  I don't know if this is a coincidence, or if there is something else that has happened that may be the source of the problem.

**Comment by Crewski** [comment]
I just installed the latest version on a different computer and ran a mock setup.  For me, the SWG setpoint was created.....however it is showing as a "read-only" entity, so it isn't shown in the device screen or even that the entity was created by njs-pc.  It says it was created by number.  It does work however.  I need to figure out why that is happening, but it still should be in your list.  Any errors in the logs?
![image](https://user-images.githubusercontent.com/8012153/210135649-e6cb5ea0-b4b4-4cc1-a7ae-5d446fd5e7ea.png)

**Comment by FlaMike** [comment]
On my system, it shows up as part of njsPC-HA, not a number.  I do have the error indicator, but I didn't find anything in the logs.  For what it's worth, here are a few screen shots.  Spa salt setpoint and spa heater are also listed an unavailable, but I don't have a spa, so that may not be relevant.

![image](https://user-images.githubusercontent.com/41341956/210136149-dfccf872-0c26-4e7f-89e2-6f185e772691.png)


![image](https://user-images.githubusercontent.com/41341956/210135959-1446b929-886f-481c-862d-dd0e1fc1132f.png)

![image](https://user-images.githubusercontent.com/41341956/210136008-5ba6aa78-23b8-4613-9bb9-ce9c8e84447c.png)

**Comment by Crewski** [comment]
Hmmmm....its acting like the unique ID changed on it or something along those lines.  What if you delete the integration and then re-add it?

**Comment by FlaMike** [comment]
I tried that before I sent you a message a few hours ago.  No love at this end.

**Comment by Crewski** [comment]
I figured, but had to ask.  I assume it shows up in dashPanel properly.

I'll have to think about this one.  Along with the changes for your heater, there were the changes of adding entities to a device.  I wonder if its related to that.

**Comment by FlaMike** [comment]
Sounds like that may be related.

I'm available if you need someone to test stuff, of course.

**Comment by FlaMike** [comment]
FYI, a few minutes ago I saw that the salt cell setpoint came back to life!  I did restart HA a couple of times this morning, but I had done so since downloading the update yesterday.  Very odd.
