### ISSUE TITLE
sensor.intellichlor_20_salt_required is always zero

### ISSUE THREAD

**Issue by FlaMike** [Crewski/njsPC-HA#15]
For the past few weeks, the value sensor.intellichlor_20_salt_required has been zero even though the target salt level is several hundred ppm above the reported salt level in the pool.  I am running version 4.1 of njs-PC-HA.  I believe this issue began when I installed the 4.1 update.  All other sensor values appear to be OK.

I have reloaded both the HACS njs-PC (and restarted HA) and the HA integration without any changes in the value of this sensor.

While this is not a  huge deal--I still get reported salt values and target salt values so I can tell if I need to add salt, I thought I should bring this to your attention.

Thanks again for this fabulous program & your excellent help & support!

**Comment by FlaMike** [comment]
As always, thank you for your quick response!

Life as my salt cell is certainly challenging these days :-0

The poolController url shows a saltRequired value of 0, so it appears the challenge is not in your integration.  I guess I should send a note to the poolController folks.

FYI, below is the entire response from the poolController.  Interestingly, it also shows an output value of 8% even though the salt cell is off due to low temperature of the water.  So I guess they have two issues, at least in my pool.

{"id":1,"disabled":false,"isActive":true,"spaSetpoint":10,"poolSetpoint":8,"body":{"val":32,"name":"poolspa","desc":"Pool/Spa"},"name":"Intellichlor--20","type":{"val":0,"name":"pentair","desc":"Pentair"},"saltLevel":2850,"saltRequired":0,"status":{"val":0,"name":"ok","desc":"Ok"},"superChlorHours":8,"superChlor":false,"superChlorRemaining":0,"targetOutput":8,"model":{"val":2,"name":"intellichlor--20","desc":"IntelliChlor IC20","capacity":20000,"chlorinePerDay":0.7,"chlorinePerSec":0.000008101851851851852},"lastComm":1673984950152,"currentOutput":8,"equipmentType":"chlorinator","saltTarget":3400}

**Comment by Crewski** [comment]
I'll go ahead and close this as its a nodejs-poolController problem.  Hopefully they'll get it figured out for you quickly.
