### ISSUE TITLE
Device and entities become unavailable occasionally

### ISSUE THREAD

**Issue by nicksardo** [Crewski/njsPC-HA#16]
Since the last release, I've beginning to see the entities become unavailable and they only become available after I reload the integration. I'm not positive, but this seems to sometimes occur after HA core updates/restarts. 

I'm running the latest versions of everything. I've tried enabling remote logging for the integration, but I haven't seen anything related yet in the log.

**Comment by Crewski** [comment]
I wonder if the socket.io connection is timing out and not reconnecting.  If you revert back to an early version of njsPC-HA does it still happen?  In HACS -> njsPC-HA you can redownload via the 3-dot menu and pick the version you want.  Let me know if the issue goes away when you downgrade.

**Comment by Crewski** [comment]
@nicksardo, keep an eye on this with the latest update we just worked through.  Let me know if the entities still come and go or not.  Thanks.
