### ISSUE TITLE
v0.4.2 dropped sensors like pump rpm & salt level

### ISSUE THREAD

**Issue by nicksardo** [Crewski/njsPC-HA#19]
After upgrading to [v0.4.2](https://github.com/Crewski/njsPC-HA/releases/tag/v0.4.2), many sensor entities went unavailable; most importantly, intelliflo RPM and intelliclor salt level. I tried deleting the integration and re-adding; they still haven't popped up.

**Comment by Crewski** [comment]
Well that's not ideal!  There was some pretty decent changes in this version as @rstrouse  helped rewrite/format a bunch of stuff.  What version of Home Assistant are you running?  Also, can you post the response you get by going to `http://<your_njspc_ip>:4200/state/all`.  Thanks.

**Comment by Crewski** [comment]
Thanks.  I'll look it over.

Did you see any errors in the Home Assistant logs when you boot up?

**Comment by rstrouse** [comment]
@nicksardo go into your devices list for njsPC-HA on home assistant and click on the pump.  It is possible that since we had some overlapping ids in HA that these are simply on a different id.  If you go to your dashboard make sure they are assigned to the correct entity.

**Comment by rstrouse** [comment]
Go into settings and on the integration click reload on the njsPC-HA integration.

**Comment by rstrouse** [comment]
If you upload your poolState.json and poolConfig.json I can mimic your install to see if there is anything in the output that does not show up.  In your Home Assistant logs are you seeing any .... entity id duplicated messages.  Home assistant will simply not create an entity if it already exists for the given unique id.   Strangely, deleting the integration does not always clean these up.  When you click on entities for the integration do you see any that are dead?

**Comment by Crewski** [comment]
@rstrouse I'll defer to you since I don't have chemical controllers, but seems like we just need to set the name to "unknown" then replace it if its available.

@nicksardo thanks for the heads up on that alert.  Its a simple single line change so I'll include it in the next release.

**Comment by rstrouse** [comment]
@nicksardo do you have a chemistry controller?  How did you get one added to njsPC without a name?

**Comment by rstrouse** [comment]
Stop njsPC and edit the poolConfig.json.  Scroll down to the chem controllers section and delete the single entry that is in there.  But if EasyTouch thinks its there but just cannot communicate with it, it will try to put it back.

Do you have IntelliChem enabled on your EasyTouch?  Perhaps it is still trying to communicate with that and if it doesn't exist it will do all manner of crappy things in EasyTouch to try to resurrect it.
