### ISSUE TITLE
Some entities do not appear to update until integration is reloaded in HA

### ISSUE THREAD

**Issue by FlaMike** [Crewski/njsPC-HA#26]
I am running njsPC version 8.0.1 and njsPC-HA version 0.4.3-b3 with a Pentair EasyTouch 2 4.  At least one entity in HA is not updated regularly, specifically, the pool salt concentration.  When I reload the integration, the value is updated & agrees with the dashPanel.  

This  issue came to light this week because we had nearly 6" of rain in two days & the pool overflow was working overtime.  I'm trying to recover & get the water chemistry back to where it's been.  I knew the salt level was low, but had no idea what it was because the reported value in HA had not updated.  I reloaded the integration &  the salt level updated & then agreed with the dashPanel.  I  added a bag  of salt &  waited a day, but the value in HA had not updated.  I reloaded the integration again, & it was updated & agreed again with the dashPanel.  

I'm not certain if there are other entities that are not updated as well.  Water flow, pump status, pump speed, pump power draw, air & water temperature, cleaner status, heater status, freeze status, & pool lights all appear to be current & updated regularly.

If I may provide additional information or test any code changes, please let me know.

Thank you!

**Comment by Crewski** [comment]
Thanks for reporting this.  I opened my pool last week and noticed the same thing with the salt sensor, I just haven't dug into it yet beside a quick look.  It seems specific to that sensor because all the other update like you said.

**Comment by FlaMike** [comment]
No worries & no hurry on my part.  When I realized I could get the "real" reading from the dashPanel or by reloading the integration, I figured I all was good.  I just wanted to let you know since I figured others may run into the issue--as did you.

Glad you're opened your pool--I'm looking forward to diving in as well!  It seems like every time we finally warm up & I'm ready to heat the pool the final 10 degrees, we've had a storm that brought the temperature down 10-15 degrees.  I'm about to say the heck with it & blow the gas bill.  I had the pool chemistry spot on before we were soaked this past week.  Now it will likely be a few days to get the salt, sodium bicarb, calcium, & arsenic back in order.  I generally adjust them 1 at a time & check the following day before moving onto the next chemical.  Of course, salt, Cl, and pH are the most important, particularly in the short run.  Once they're set, it's time to crank up the heater!

As I said, if  I can help in any way, please let me know!

**Comment by Crewski** [comment]
@FlaMike I just pushed out v0.4.4 which should correct the issue with the salt sensor.  I'll close this.  If it doesn't work please reopen and let me know!

Definitely good to get the pool open.  We used a different company to close it last year and they did it when we weren't home, so who knows how they did things.  Algae was floating around everywhere.  Finally got it all clean and clear....just need to weather to warm up.  I got a heat pump so it takes a while for me to get my temps up.  Currently sitting at 70 until it looks like the weather will be swimming weather.
