### ISSUE TITLE
Add Support for Covers

### ISSUE THREAD

**Issue by treyrich** [Crewski/njsPC-HA#28]
It would be great to add support for covers so that you can trigger certain automations only if a pool is covered/uncovered. 

I’m typing this out from my phone, but I expect that this is fairly trivial to expose a binary sensor for each cover. I can potentially look into doing a PR for it tomorrow when at my computer.

**Comment by Crewski** [comment]
I completely agree that it would be great to have covers supported.  I know I have to change my SWG depending on whether or not my solar cover is on.  With that said, is that a part of nodejs-PoolController?  I know that the data has an "isCovered" field for bodies but I've never seen it mentioned before or in the interface anywhere.

**Comment by treyrich** [comment]
Yes, it is supported in njspc, it’s primarily used for auto covers, I’m not aware of anyone that uses it with a solar cover. You have to get a cover expansion card for intellicenter, and then have a low voltage wire run between the cover and the expansion card indicating whether it’s covered or not. 

With that setup though it definitely indicates whether it’s covered or not in the njspc dashboard:
![IMG_2183](https://github.com/Crewski/njsPC-HA/assets/1641028/1c428bf3-4733-43e0-803b-bb9a22beb43d)

**Comment by Crewski** [comment]
Ah, gotcha.  I just have the DIY NIxie controller setup.  I always wondered about the how the "isCovered" data is set.  I'll take a look at it, should be easy enough.

**Comment by treyrich** [comment]
So I just looked at the JSON, looks like you could use the `isCovered` property on the bodies, but there's also a top-level property of `covers` which contains the following:
```json
[
  {
    "id": 1,
    "isClosed": true,
    "name": "Cover 1",
    "equipmentType": "cover"
  }
]
```

I think the better way to approach this is to just expose each cover as a sensor itself. The expansion card supports up to 2 covers, I only have one, but I think it may make more sense to just expose the cover rather than whether the body is covered...But maybe both would be smart. If I get a chance today I'll look into this a bit more and see what I can do.

**Comment by treyrich** [comment]
Yes, I actually think that this works great. I need to go out and open and close the cover to ensure that it is updating as expected. But overall I think this will work great. While I do think that there could be value in having the separate covers entities, I think the way it's setup now fulfills the desire that led me to originally create this issue. Let me confirm that it works when I open and close and if so then I will close this issue. Thanks for such a quick turn around on this! You got to it before I could even think about a PR haha

**Comment by treyrich** [comment]
Ok. Just tested it, it works perfect! Thanks again for the quick turn around!

**Comment by treyrich** [comment]
Actually, going to reopen, I think that we should have this exposed as a `binary_sensor`, not as a `sensor`. Any idea why it didn't expose a `binary_sensor`?

**Comment by Crewski** [comment]
Give v0.4.6 a try.
