### ISSUE TITLE
pH Behavior

### ISSUE THREAD

**Issue by subcritical71** [Crewski/njsPC-HA#32]
Hi, thanks for the great HA add-on. 

I just got my pH/ORP sensors working and I am noticing a strange behavior on the HA integration. 

I did a reload and it appears all the ORP sensor data is now inside HA. The pH though is not appearing (I assume it should be under REM Chem). I don't have an Acid tank yet so I left 'pH enabled' as off. But when I turn it to on I loose all my ORP sensors (state changes to Unknown) and only gain the pH setpoint entity. Subsequently disabling the pH brings the ORP sensors back and I loose the pH setpoint.

Any idea if this may be a config issue on my end?

**Comment by Crewski** [comment]
I don’t have that equipment so I’m going to be guessing. Someone else had an issue where they had their tank size in njsPC as 0, which was causing a problem. Maybe take a look at that, even though you don’t have one. 

Do you see any errors in the log?

**Comment by subcritical71** [comment]
I changed the tank level and did notice (after you mentioned it) the log file indicating a division by zero error. The only thing I'd like to mention is that if you are only monitoring the pH like I am the pH enabled option in dash panel would normally be unchecked. I have to check it and place everything in manual for the pH readings to show up. I know it's difficult to troubleshoot when you don't have the equipment so I can live with that work around. Its not like I'll be dosing with a non-existent tank! :)

**Comment by Crewski** [comment]
@subcritical71 sorry for the slow response, I've been on vacation.  When you do not have pH enabled, do you still get a pH demand?  I'm assuming you do but wanted to check before I move the sensors out from under the "enabled" criteria.

**Comment by subcritical71** [comment]
@Crewski Now it is I who had the long delay in response! To answer your question, I loose everything when I disable pH (on the pH side of things). I put the dosing into manual and other than some dosing messages on dash panel it works fine ('pH daily limit reached', and I can't remember the second one).

pH enabled
<img width="325" alt="Screen Shot 2023-07-03 at 7 18 19 AM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/0e8dec82-3479-4f3d-ab4d-9872ee233e5a">

pH disabled
<img width="324" alt="Screen Shot 2023-07-03 at 7 17 03 AM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/5b809968-115b-4450-9fec-57d98614e1f7">

**Comment by Crewski** [comment]
@subcritical71 No worries!  I pushed out v0.4.8.  It should move the ph/orp level and demand sensors outside of the "enabled" requirement.  Let me know if it works.

**Comment by subcritical71** [comment]
Just updated to 0.4.8. Looks like the issue is solved. Thanks!
