### ISSUE TITLE
Alkalinity input box cropped

### ISSUE THREAD

**Issue by psmith3** [Crewski/njsPC-HA#33]
Hi Crewski, I am seeing an issue with the Alkalinity input box in the integration that makes it difficult to see and input the value of my alkalinity. Is this an issue in the integration or is it specific to me somehow? See screen capture attached. ![image](https://github.com/Crewski/njsPC-HA/assets/14373163/5095979e-9de1-4655-95ba-cb6026e2e2ad)

**Comment by Crewski** [comment]
This shouldn't be related to the integration as that all of those are generated from the same sensor template.  Are you able to easily read it if you click on the entity or add it to a dashboard?

**Comment by psmith3** [comment]
Same problem when I click on the gearbox and try to read it directly. The box is cropped.


On Jun 26, 2023, at 1:14 PM, Crewski ***@***.***> wrote:

﻿

This shouldn't be related to the integration as that all of those are generated from the same sensor template. Are you able to easily read it if you click on the entity or add it to a dashboard?

**Comment by Crewski** [comment]
The snapshot didn't get put in your message.  I wonder if its having issues with padding/margins.  If you were to override the name "Total Alkalinity" to just "Alkalinity" would it work properly?

**Comment by psmith3** [comment]
![image](https://github.com/Crewski/njsPC-HA/assets/14373163/9ae4bc02-8505-405e-a9bd-a37208a139dd)
Sorry, I Replied via email before. Here you go.

**Comment by psmith3** [comment]
No, that did not make a difference. 
![image](https://github.com/Crewski/njsPC-HA/assets/14373163/ac2d7b31-d6c8-4cf0-b920-1d1d5955f7b3)
![image](https://github.com/Crewski/njsPC-HA/assets/14373163/ccfbb09d-5b63-4e3c-a708-8d998a18880f)

**Comment by Crewski** [comment]
I finally got it set up in my test environment....it's definitely not just you.  Something is weird with the Alkalinity.  I'll have to dig deeper into it.

**Comment by Crewski** [comment]
Try out v0.4.10 that I just pushed out.  There was a typo setting the min/max for the number box.  I think that will fix the issue you are having.  Let me know!

**Comment by psmith3** [comment]
Fixed! Thanks much.
