### ISSUE TITLE
No salt water generator entities in Home Assistant

### ISSUE THREAD

**Issue by FlaMike** [Crewski/njsPC-HA#4]
I have a Pentair Easytouch 2 4 controller.  I just installed your integration via HACS (thanks for your help!) and am going through the entities to add to my automations & HA dashboard.  I do not have any entities that relate to the salt cell on my system in njsPC-HA.  Salt cell information also does not show up on the poolController dashboard.  Is there something I need to do in order to get salt cell information in the poolController and into HA?

Thank you!

**Comment by Crewski** [comment]
@FlaMike if the salt values aren't showing in the nodejs-PoolController dashboard then you'll have to start there.  I don't have any experience with the Easytouch as I used the standalone Nixie controller in nodejs-PoolController.

For this integration, all the information is initially pulled from the /state/all request.  You can see the information by making a GET call (or just type the address in your browser) to http://<youripaddress>:4200/state/all.

Sorry I can't be of more help on this, though I sure the nodejs-PoolController guys will get you squared away in no time.

**Comment by FlaMike** [comment]
All good now!  I was able to add the chlorinator & the entities needed into HA and updated my automations appropriately,  Thank you for letting me know about your software and your help in getting things going!

![image](https://user-images.githubusercontent.com/41341956/192163862-2f915183-1da1-4e40-b30d-fc147fba249b.png)
