### ISSUE TITLE
Integration using deprecated features

### ISSUE THREAD

**Issue by matthew-hz** [Crewski/njsPC-HA#47]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1272
integration: Light (documentation, issues)
First occurred: 7:15:38 AM (15 occurrences)
Last logged: 7:15:44 AM

None (<class 'custom_components.njspc_ha.light.CircuitLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/Crewski/njsPC-HA/issues

**Comment by Crewski** [comment]
I just pushed out v0.4.13 to fix this issue.  It's untested in production since my pool isn't open yet, but working in development.  Please let me know if the issue isn't fixed.
