### ISSUE TITLE
Integration HVACModes Error

### ISSUE THREAD

**Issue by matthew-hz** [Crewski/njsPC-HA#48]
Entity None (<class 'custom_components.njspc_ha.bodies.BodyHeater'>) implements HVACMode(s): off, heat and therefore implicitly 
supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/Crewski/njsPC-HA/issues

**Comment by Crewski** [comment]
I just pushed out v0.4.13 to fix this issue.  It's untested in production since my pool isn't open yet, but working in development.  Please let me know if the issue isn't fixed.
