### ISSUE TITLE
FR: Expose all entities under a device

### ISSUE THREAD

**Issue by nicksardo** [Crewski/njsPC-HA#7]
It would be nice if the integration exposed a device with all the entities. This would be helpful to see all the states/values simultaneously. 

BTW: Thanks for the integration; works well!

**Comment by APTech-Group** [comment]
Yeah, I agree it would be better that way.  Let me figure out how to do it.

**Comment by Crewski** [comment]
Finally got around to setting this up in v0.4.0.  Thanks for the recommendation.
